services:
  app:
    build:
      context: ./app
    volumes:
      # - ./app:/app
      - ./app/src:/app/src
    command: sh -c "npm run start"
    # command: sh -c "/bin/bash"
    # tty: true
    ports:
      - "3000:3000"
    depends_on:
      - redis
  redis:
    image: redis:7.4.1-alpine
    # ports:
    #   - 6379:6379
    volumes:
      - "./redis/data:/data"